services:
  # db:
  #   image: postgres:16
  #   container_name: nikoniko_db
  #   environment:
  #     - POSTGRES_DB=nikoniko
  #     - POSTGRES_USER=nikoniko
  #     - POSTGRES_PASSWORD=nikoniko
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data # Bind mount to a local directory for backup
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U nikoniko -d nikoniko"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  backend:
    build:
      context: .
      dockerfile: api/NikoNiko.Api/Dockerfile
    container_name: nikoniko_backend
    volumes:
      - ./data:/app/data # Mount data directory
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080
      - DatabaseProvider=SQLite
      - ConnectionStrings__SQLiteConnection=Data Source=/app/data/nikoniko.db
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=nikoniko;Username=nikoniko;Password=nikoniko
      - Authentication__Jwt__Issuer=NikoNiko
      - Authentication__Jwt__Audience=NikoNikoClient
      - Authentication__Jwt__Key=${JWT_KEY}
      - Authentication__Google__ClientId=${GOOGLE_CLIENT_ID}
      - Authentication__Google__ClientSecret=${GOOGLE_CLIENT_SECRET}
      - Authentication__Microsoft__ClientId=
      - Authentication__Microsoft__ClientSecret=
      - Authentication__GitHub__ClientId=${GITHUB_CLIENT_ID}
      - Authentication__GitHub__ClientSecret=${GITHUB_CLIENT_SECRET}
      - Authentication__FrontendRedirectUrl=${FRONTEND_REDIRECT_URL}
      - SignalRService__BaseUrl=http://nikoniko_notifications:8080 # SignalR Service URL for backend
      - SUPER_ADMINS=${SUPER_ADMINS}
    healthcheck:
      test: ["CMD-SHELL", "curl -f -H 'X-Forwarded-Proto: https' http://localhost:8080/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  notifications: # New SignalR Service
    build:
      context: .
      dockerfile: api/NikoNiko.Notifications/Dockerfile
    container_name: nikoniko_notifications
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080
      - Cors__AllowedOrigins=http://localhost:3000 # Allow frontend origin
      - Authentication__Jwt__Issuer=NikoNiko
      - Authentication__Jwt__Audience=NikoNikoClient
      - Authentication__Jwt__Key=${JWT_KEY}
    healthcheck:
      test: ["CMD-SHELL", "curl -fL http://localhost:8080/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
      args:
        - VITE_GITHUB_REPO_URL=${VITE_GITHUB_REPO_URL}
    container_name: nikoniko_frontend
    depends_on:
      backend:
        condition: service_healthy
      notifications:
        condition: service_healthy